---
- name: deploying arvan cluster
  hosts: cluster
  become: true
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - name: Run Kubernetes setup
      import_tasks: main.yml

